import React from 'react';
import { ArrowLeft, FileText } from 'lucide-react';
import { Language } from '../types';

interface Props {
  onBack: () => void;
  language: Language;
}

export const TermsConditions: React.FC<Props> = ({ onBack, language }) => {
  const content = {
    en: {
      title: "Terms and Conditions",
      lastUpdated: "Last updated: January 2026",
      agreementTitle: "1. Agreement to Terms",
      agreement: "By accessing or using Le cuisinier, you agree to be bound by these Terms and Conditions. If you disagree with any part of these terms, you may not access the service.",
      aiDisclaimerTitle: "2. AI-Generated Content Disclaimer",
      accuracyTitle: "Accuracy",
      accuracy: "The recipes, cooking times, and instructions are generated by Artificial Intelligence. While we strive for accuracy, the AI may occasionally produce incorrect or unsafe instructions. Use your own judgment and common sense when cooking.",
      safetyTitle: "Safety",
      safety: "You are responsible for ensuring that ingredients used are safe for consumption and do not violate any dietary restrictions or allergies of your guests. We are not liable for any food-borne illnesses, allergic reactions, or kitchen accidents resulting from the use of this app.",
      licenseTitle: "3. Use License",
      license: "Permission is granted to temporarily download one copy of the materials (information or software) on Le cuisinier for personal, non-commercial transitory viewing only.",
      apiTitle: "4. API Usage",
      api: "If you provide your own API key, you are responsible for any charges incurred on your Google Cloud Platform account. We are not responsible for managing your API quotas or billing.",
      ipTitle: "5. Intellectual Property",
      ip: "The application code and design are the intellectual property of MickeyYKM. Copyright © 2026.",
      contactTitle: "6. Contact",
      contact: "For any inquiries regarding these terms, please contact:",
      back: "Back",
      versionNote: "If there is any inconsistency between the Chinese and English versions of these Terms and Conditions, the English version shall prevail."
    },
    'zh-TW': {
      title: "服務條款",
      lastUpdated: "最後更新：2026年1月",
      agreementTitle: "1. 同意條款",
      agreement: "透過存取或使用 Le cuisinier，即表示您同意受本服務條款的約束。如果您不同意這些條款的任何部分，則不得使用本服務。",
      aiDisclaimerTitle: "2. AI 生成內容免責聲明",
      accuracyTitle: "準確性",
      accuracy: "食譜、烹飪時間和說明均由人工智慧生成。雖然我們力求準確，但 AI 偶爾可能會產生不正確或不安全的說明。烹飪時請運用您自己的判斷和常識。",
      safetyTitle: "安全性",
      safety: "您有責任確保所使用的食材適合食用，且不違反客人的任何飲食限制或過敏原。對於因使用本應用程式而導致的任何食源性疾病、過敏反應或廚房事故，我們概不負責。",
      licenseTitle: "3. 使用授權",
      license: "授權您暫時下載 Le cuisinier 上的資料（資訊或軟體）的一份副本，僅供個人、非商業性的暫時檢視。",
      apiTitle: "4. API 使用",
      api: "如果您提供自己的 API 金鑰，您需自行負責 Google Cloud Platform 帳戶產生的任何費用。我們不負責管理您的 API 配額或帳單。",
      ipTitle: "5. 智慧財產權",
      ip: "應用程式的程式碼和設計是 MickeyYKM 的智慧財產權。版權所有 © 2026。",
      contactTitle: "6. 聯絡方式",
      contact: "有關這些條款的任何疑問，請聯繫：",
      back: "返回",
      versionNote: "本服務條款若有中英文版本不一致之處，以英文版本為準。"
    }
  };

  const t = content[language];

  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <button
        onClick={onBack}
        className="mb-8 text-brand-text/60 hover:text-brand-primary flex items-center gap-2 transition-colors font-bold bg-brand-surface px-4 py-2 rounded-full shadow-sm hover:shadow-md"
      >
        <ArrowLeft size={20} /> {t.back}
      </button>

      <div className="bg-brand-surface rounded-3xl shadow-soft p-8 md:p-12 animate-in fade-in slide-in-from-bottom-4 duration-500">
         <div className="flex items-center gap-4 mb-8 border-b border-brand-primary/10 pb-6">
            <div className="bg-brand-secondary/30 p-4 rounded-2xl text-brand-text">
                <FileText size={32} />
            </div>
            <div>
              <h1 className="text-3xl font-black text-brand-text">{t.title}</h1>
              <p className="font-medium text-sm text-brand-muted mt-1">{t.lastUpdated}</p>
            </div>
        </div>

        <div className="space-y-8 text-brand-text/80 leading-relaxed">
            <section>
                <h2 className="text-xl font-bold text-brand-text mb-3 flex items-center gap-2">
                   {t.agreementTitle}
                </h2>
                <p>{t.agreement}</p>
            </section>

             <section>
                <h2 className="text-xl font-bold text-brand-text mb-3 flex items-center gap-2">
                   {t.aiDisclaimerTitle}
                </h2>
                <div className="bg-red-50 p-4 rounded-xl border border-red-100">
                  <p className="mb-2 text-red-800"><strong>{t.accuracyTitle}:</strong> {t.accuracy}</p>
                  <p className="text-red-800"><strong>{t.safetyTitle}:</strong> {t.safety}</p>
                </div>
            </section>

            <section>
                <h2 className="text-xl font-bold text-brand-text mb-3 flex items-center gap-2">
                   {t.licenseTitle}
                </h2>
                <p>{t.license}</p>
            </section>

            <section>
                <h2 className="text-xl font-bold text-brand-text mb-3 flex items-center gap-2">
                   {t.apiTitle}
                </h2>
                <p>{t.api}</p>
            </section>

            <section>
                <h2 className="text-xl font-bold text-brand-text mb-3 flex items-center gap-2">
                   {t.ipTitle}
                </h2>
                <p>{t.ip}</p>
            </section>

             <section>
                <h2 className="text-xl font-bold text-brand-text mb-3 flex items-center gap-2">
                   {t.contactTitle}
                </h2>
                <p>{t.contact}</p>
                <a href="mailto:admin@mickey-calligraphy.art" className="inline-block mt-2 font-bold text-brand-primary bg-brand-primary/10 px-4 py-2 rounded-lg hover:bg-brand-primary hover:text-white transition-colors">
                  admin@mickey-calligraphy.art
                </a>
            </section>

            {language !== 'en' && (
              <section className="pt-6 border-t border-brand-muted/20">
                 <p className="text-sm text-brand-muted italic">
                   {t.versionNote}
                 </p>
              </section>
            )}
        </div>
      </div>
    </div>
  );
};